name: football_mpt_project
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - opencv
  - pytorch
  - torchvision
  - torchaudio
  - matplotlib
  - scikit-learn
  - black
  - pip
  - pip:
      - ultralytics
